### ISSUE TITLE
Fails when using hdf5 canonical

### ISSUE THREAD

**Issue by brtnfld** [Parallel-NetCDF/E3SM-IO#126]
mpiexec -n 16 ./e3sm_io f_case_866x72_16p.nc -k -o F_out.h5 -x canonical -a hdf5 -r 10
Error in ../../../src/cases/var_wr_case.cpp line 312 function var_wr_case
Error in ../../../src/cases/var_wr_case.cpp line 312 function var_wr_case
Error in ../../../src/cases/var_wr_case.cpp line 312 function var_wr_case
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 2

**Comment by khou2020** [comment]
Can you try the latest fix?

**Comment by brtnfld** [comment]
That fixed it, thanks.
