### ISSUE TITLE
e3sm_io_print_profile()

### ISSUE THREAD

**Issue by wkliao** [Parallel-NetCDF/E3SM-IO#65]
e3sm_io_print_profile() seems only relevant to HDF5 and
dumps HDF5 timing breakdowns. It should be called in the
verbose or debug mode only.

https://github.com/Parallel-NetCDF/E3SM-IO/blob/a92d517667ce1d4439fbfd9a6db1ff63f8efeded/src/e3sm_io_core.cpp#L113

Also, what is the first column of each line for? i.e. `#%$:`
```
#%$: e3sm_io_timer_hdf5_time_mean: 0.000000
```

**Comment by khou2020** [comment]
Dear Professor Liao:

It is unfinished. I plan to move other E3SM timers into print profile.

Respectfully yours,
kaiyuan

From: Wei-keng ***@***.***>
Sent: Sunday, July 11, 2021 17:52
To: ***@***.***>
Cc: ***@***.***>
Subject: [Parallel-NetCDF/E3SM-IO] e3sm_io_print_profile() (#65)


e3sm_io_print_profile() seems only relevant to HDF5 and
dumps HDF5 timing breakdowns. It should be called in the
verbose or debug mode only.

https://github.com/Parallel-NetCDF/E3SM-IO/blob/a92d517667ce1d4439fbfd9a6db1ff63f8efeded/src/e3sm_io_core.cpp#L113

Also, what is the first column of each line for? i.e. #%$:

#%$: e3sm_io_timer_hdf5_time_mean: 0.000000

**Comment by wkliao** [comment]
I made it in verbose mode only in 230c64197bafc07c16045296bc35e004f7df9450
